import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-primary",
  subsets: ["latin"],
});

const satoshi = localFont({
  src: [
    { path: "../fonts/satoshi/Satoshi-Regular.otf", weight: "400" },
    { path: "../fonts/satoshi/Satoshi-Medium.otf", weight: "500" },
    { path: "../fonts/satoshi/Satoshi-Medium.otf", weight: "700" },
    { path: "../fonts/satoshi/Satoshi-Medium.otf", weight: "900" },
  ],
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${satoshi.variable} font-primary bg-[#F9F9F9] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
